version: 2

updates:
  ##################################################
  # Python Packages
  ##################################################

  - package-ecosystem: "pip"

    directory: "/"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

  ##################################################
  # GitHub Actions
  ##################################################

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

  ##################################################
  # Docker
  ##################################################

  - package-ecosystem: "docker"

    directory: "/"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

  ##################################################
  # Terraform
  ##################################################

  - package-ecosystem: "terraform"

    directory: "/terraform"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5
