skip-check:
  - CKV_AWS_88
  - CKV_AWS_135
  - CKV_AWS_136
  - CKV_AWS_130
  - CKV_AWS_260
  - CKV_AWS_382
  - CKV_AWS_24
  - CKV_AWS_23
  - CKV2_AWS_11
  - CKV2_AWS_12
  - CKV_AWS_51 # Portfolio project uses mutable ECR tags for CI/CD with the latest image
