apiVersion: v1
kind: Secret

metadata:
  name: pawfolio-secret
  namespace: pawfolio

type: Opaque

stringData:
  SECRET_KEY: "change-me-later"

  POSTGRES_USER: "pawfolio"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "pawfolio"

  DATABASE_URL: "postgresql://pawfolio:password@postgres:5432/pawfolio"
