"""add vaccination completion status

Revision ID: 1582af921861
Revises: 2b8ddbbdce6b
Create Date: 2026-08-15 13:20:24.287983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1582af921861'
down_revision = '2b8ddbbdce6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'completed',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
