"""Add VetVisit table

Revision ID: 38eb66f32967
Revises: 75513bbd385b
Create Date: 2026-07-25 01:09:28.625894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38eb66f32967'
down_revision = '75513bbd385b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('clinic_name', sa.String(length=150), nullable=False),
    sa.Column('veterinarian', sa.String(length=150), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vet_visit')
    # ### end Alembic commands ###
