"""Recreate vaccination table with date columns

Revision ID: 75513bbd385b
Revises: cc017dba7367
Create Date: 2026-07-24 15:09:54.680587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75513bbd385b'
down_revision = 'cc017dba7367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('date_given', sa.Date(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('veterinarian', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination')
    # ### end Alembic commands ###
