"""Remove Pet.weight and use WeightRecord as source of truth

Revision ID: cd344adbe9e3
Revises: fffc6f1486c0
Create Date: 2026-07-31 13:40:01.726159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd344adbe9e3'
down_revision = 'fffc6f1486c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_record_pet_id'), ['pet_id'], unique=False)

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_record_pet_id'))

    op.drop_table('weight_record')
    # ### end Alembic commands ###
