"""Add medication table

Revision ID: fffc6f1486c0
Revises: 6bdacc506cf3
Create Date: 2026-07-29 13:04:28.368776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffc6f1486c0'
down_revision = '6bdacc506cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_pet_id'), ['pet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_pet_id'))

    op.drop_table('medication')
    # ### end Alembic commands ###
