apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pawfolio-secret
  namespace: pawfolio
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: pawfolio-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: pawfolio/app
        property: DATABASE_URL

    - secretKey: GOOGLE_CLIENT_SECRET
      # checkov:skip=CKV_SECRET_6: External Secrets references a remote secret; no secret value is stored in Git
      remoteRef:
        key: pawfolio/app
        property: GOOGLE_CLIENT_SECRET

    - secretKey: POSTGRES_DB
      remoteRef:
        key: pawfolio/app
        property: POSTGRES_DB

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: pawfolio/app
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_USER
      remoteRef:
        key: pawfolio/app
        property: POSTGRES_USER

    - secretKey: SECRET_KEY
      remoteRef:
        key: pawfolio/app
        property: SECRET_KEY
