apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - config/configmap.yaml
  - secrets/secret.yaml

  - postgres/postgres-pvc.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml

  - pawfolio-deployment.yaml
  - pawfolio-service.yaml

  - ingress/ingress.yaml

  - hpa/hpa.yaml
