apiVersion: v1
kind: Service

metadata:
  name: pawfolio-service
  namespace: pawfolio

spec:
  type: ClusterIP

  selector:
    app: pawfolio

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
