apiVersion: v1
kind: ConfigMap

metadata:
  name: pawfolio-config
  namespace: {{ .Release.Namespace }}

data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  FLASK_DEBUG: {{ .Values.config.FLASK_DEBUG | quote }}
  