apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "pawfolio.fullname" . }}
  namespace: {{ .Release.Namespace }}

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
{{ include "pawfolio.selectorLabels" . | indent 6 }}

  template:
    metadata:
      labels:
{{ include "pawfolio.selectorLabels" . | indent 8 }}

    spec:
      containers:
        - name: pawfolio

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: pawfolio-config
            - secretRef:
                name: pawfolio-secret

          resources:
{{ toYaml .Values.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            