apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "pawfolio.fullname" . }}-dora
  namespace: {{ .Release.Namespace }}

  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pawfolio-dora
      app.kubernetes.io/instance: {{ .Release.Name }}

  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
