apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "pawfolio.fullname" . }}-dora
  namespace: {{ .Release.Namespace }}

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

automountServiceAccountToken: false
