apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

spec:
  type: {{ .Values.postgres.service.type }}

  selector:
    app: postgres

  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
      