apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

  annotations:
    checkov.io/skip1: CKV_K8S_20=Official PostgreSQL image security model
    checkov.io/skip2: CKV_K8S_22=PostgreSQL requires a writable data directory
    checkov.io/skip3: CKV_K8S_23=Official PostgreSQL image runs as UID 999
    checkov.io/skip4: CKV_K8S_28=Official PostgreSQL image default networking
    checkov.io/skip5: CKV_K8S_37=Capabilities required by the official PostgreSQL image
    checkov.io/skip6: CKV_K8S_40=Official PostgreSQL image runs as UID 999 by design
    checkov.io/skip7: CKV_K8S_43=Official PostgreSQL image referenced by version tag

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

spec:
  replicas: 1

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      automountServiceAccountToken: false

      terminationGracePeriodSeconds: 30

      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}

      containers:
        - name: postgres

          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}

          ports:
            - containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: postgres-storage

          persistentVolumeClaim:
            claimName: postgres-pvc
            