apiVersion: v1
kind: Secret

metadata:
  name: pawfolio-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  