{{- if .Values.secret.create }}

apiVersion: v1
kind: Secret

metadata:
  name: pawfolio-secret
  namespace: {{ .Release.Namespace }}

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

type: Opaque

stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}

{{- end }}
