{{- if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ default (include "pawfolio.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}

  labels:
{{ include "pawfolio.labels" . | indent 4 }}

automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

{{- end }}
