name: Terraform Validation

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main
      - ui-redesign

permissions:
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: Validate Terraform

    runs-on: ubuntu-latest

    timeout-minutes: 15

    env:
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

    defaults:
      run:
        working-directory: terraform

    steps:
      ##################################################
      # Checkout Repository
      ##################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ##################################################
      # Setup Terraform
      ##################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.8"

      ##################################################
      # Create Plugin Cache Directory
      ##################################################

      - name: Create Terraform Plugin Cache Directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      ##################################################
      # Cache Terraform Providers
      ##################################################

      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      ##################################################
      # Terraform Formatting
      ##################################################

      - name: Terraform Format Check
        run: |
          set -euo pipefail
          terraform fmt -check -recursive

      ##################################################
      # Terraform Init
      ##################################################

      - name: Terraform Init
        run: |
          set -euo pipefail
          terraform init -backend=false

      ##################################################
      # Terraform Validation
      ##################################################

      - name: Terraform Validate
        run: |
          set -euo pipefail
          terraform validate

      
      ##################################################
      # Checkov Scan
      ##################################################

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
